//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vic_process_closuserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FechaEjecucion
    {
        public int FechaEjecucionID { get; set; }
        public int PlanFechaEjecucionID { get; set; }
        public string RazonDeEjecucion { get; set; }
        public System.DateTime FechaEjecucion1 { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public bool PermitirVariosReprocesos { get; set; }
        public bool Estado { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
