//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vic_process_closuserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogsID { get; set; }
        public System.Guid ProcesoGUID { get; set; }
        public string ProcesoNombre { get; set; }
        public System.DateTime FechaEjecucion { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public int EstatusDelProceso { get; set; }
        public string MensajeError { get; set; }
        public string ReEjecutadoCodigo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    }
}
