//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vic_process_closuserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanFechaEjecucion
    {
        public int PlanFechaEjecucionID { get; set; }
        public string Plan { get; set; }
        public string QueryGenerator { get; set; }
        public bool Estado { get; set; }
        public System.Guid Guid { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string type_fecha { get; set; }
    
        public virtual CantidadFechaEjecucion CantidadFechaEjecucion { get; set; }
    }
}
