//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vic_process_closuserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class procesoFechasCierre
    {
        public int ID { get; set; }
        public int ID_process { get; set; }
        public int day_clouser { get; set; }
        public bool Active { get; set; }
    
        public virtual Proceso Proceso { get; set; }
    }
}
