//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vic_process_closuserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proceso()
        {
            this.procesoFechasCierres = new HashSet<procesoFechasCierre>();
        }
    
        public int ProcesoID { get; set; }
        public Nullable<int> PlanFechaEjecucionID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public System.Guid GuidRelacional { get; set; }
        public bool PermitirNotificaciones { get; set; }
        public bool PermitirRecordatorioCalendario { get; set; }
        public bool PermitirUltimoEstatusCalendario { get; set; }
        public bool RepetirProcesoDespuesFallo { get; set; }
        public int MaximaRepeticionDeProceso { get; set; }
        public Nullable<int> ProcesoIDDependiente { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procesoFechasCierre> procesoFechasCierres { get; set; }
    }
}
