//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vic_process_closuserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListJobs
    {
        public string name { get; set; }
        public string description { get; set; }
        public byte enabled { get; set; }
        public string serverName { get; set; }
    }
}
